# Generated by Django 2.2.18 on 2021-04-01 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210402_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_form',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 1, 23, 4, 44, 14124, tzinfo=utc), verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 23, 4, 44, 13126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='возраст'),
        ),
    ]
