# Generated by Django 2.2.18 on 2021-04-02 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210402_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 13, 47, 23, 993706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], default='M', max_length=128, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, default='EN', max_length=128, verbose_name='Язык'),
        ),
    ]
